# Generated by Django 3.0.8 on 2020-07-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='value',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
