# Generated by Django 3.0.8 on 2020-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200722_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='type',
            field=models.CharField(choices=[('P', 'prog'), ('W', 'web'), ('D', 'db'), ('C', 'CloudAnalytics'), ('O', 'other')], max_length=25),
        ),
    ]
