# Generated by Django 3.0.8 on 2020-07-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200726_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='type',
            field=models.CharField(choices=[('prog', 'prog'), ('web', 'web'), ('db', 'db'), ('CloudAnalytics', 'CloudAnalytics'), ('other', 'other')], max_length=25),
        ),
    ]
