# Generated by Django 3.0.8 on 2020-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200726_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='type',
            field=models.CharField(choices=[('prog', 'Programming'), ('web', 'Web Technologies'), ('db', 'Database'), ('CloudAnalytics', 'CloudAnalytics'), ('other', 'Other')], max_length=25),
        ),
    ]
